### ISSUE TITLE
Collaborer sur un nouveau projet - vinted scrapping

### ISSUE THREAD

**Issue by MichalKlg** [aime-risson/vinted-api-wrapper#10]
Hello Aimé,
J'espère que tu vas bien !

Il n'y a pas d'erreurs sur ton projet (du moins je n'en ai pas vu ;) ) , mais je voulais te contacter et je n'ai pas trouver d'autres moyen...

Je suis Michal et je travaille pour une société qui développe des projets informatiques. Nous travaillons sur un projet de développement d'un bot Vinted sur discord.
L'idée serait d'aider des utilisateurs à trouver des objets qu'ils recherchent en scrappant la plateforme et en leur notifiant lors de la publication d'un nouvel objet. 
La fonctionnalité de recherche serait similaire à ce que propose https://vintalert.com/.

Nous recherchons un profile sur Malt/upwork, mais je pense que ça pourrait être plus facile avec une personne ayant déjà travaillé sur un projet similaire, ça serais le freelancer parfait :)
Est-ce que tu serais intéressé pour développer ce type de projet? 

Je suis disponible sur michal.klg@gmail.com

Bien cordialement,
Michal

**Comment by aime-risson** [comment]
répondu par mail :)
