### ISSUE TITLE
Http error 403

### ISSUE THREAD

**Issue by Twisy9** [aime-risson/vinted-api-wrapper#9]
I have a http 403 error when I use pyVinted.

**Comment by natbrood** [comment]
Same here

**Comment by johnomon** [comment]
same

**Comment by Federico-lab** [comment]
same

**Comment by shulgadanilazxc** [comment]
same

**Comment by shulgadanilazxc** [comment]
guys use urllib3==1.24.3
Worked for me


> I have a http 403 error when I use pyVinted.



> Same here



> same



> same

**Comment by aime-risson** [comment]
Hi @shulgadanilazxc thanks for your feedback, i'll try updating the sdk

**Comment by aime-risson** [comment]
what urlib version were you using before that @shulgadanilazxc ? Version 2.0.3 is working fine for me

**Comment by natbrood** [comment]
Its working fine for me again

**Comment by shulgadanilazxc** [comment]
> what urlib version were you using before that @shulgadanilazxc ? Version 2.0.3 is working fine for me

Sorry I dont remember but updating only urllib3 helped me, I didn't change anything else
